#import '../../fragment/WeatherReportFragment.gql'

query GetWeatherReports(
  $first: Int
  $skip: Int
  $orderBy: [WeatherReportOrder]
) {
  weatherReports(first: $first, skip: $skip, orderBy: $orderBy) {
    ...WeatherReportFragment
  }
  weatherReportsMeta {
    count
  }
}
