#import '../../fragment/WeatherReportFragment.gql'

query GetWeatherReports(
  $first: Int
  $skip: Int
  $orderBy: [WeatherReportOrder]
  $filter: WeatherReportFilter
) {
  weatherReports(
    first: $first
    skip: $skip
    filter: $filter
    orderBy: $orderBy
  ) {
    ...WeatherReportFragment
  }
  weatherReportsMeta(filter: $filter) {
    count
  }
}
