fragment WeatherReportFragment on WeatherReport {
  id
  title
  startTime
  endTime
  avgTemperature
  avgPressure
  avgHumidity
  avgCloudCover
  avgWindSpeed
  dataPointsCount
  createdAt
  updatedAt
}
